#!/bin/bash

[ "$EUID" -eq 0 ] || { echo 'Please run as root. Exiting.' && exit; }

wget https://raw.githubusercontent.com/onapcraft/onap/main/onap -O /usr/bin/onap
wget https://raw.githubusercontent.com/onapcraft/onap/main/onapd -O /usr/bin/onapd

chmod +x /usr/bin/onap
chmod +x /usr/bin/onapd

onap install onap

echo 'success, install a package with "sudo onap install <package-name>".'

rm install
